# docker环境配置
zeta:
  redis:
    database: 0
    ip: 192.168.1.2
    port: 6379
    password: ''
  # 数据源配置
  database:
    url: jdbc:mysql://192.168.1.2:3306/zeta_kotlin?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 'root'
    druid:
      # druid web监控台是否启动
      WebConsoleEnabled: true
      login-username: admin
      login-password: admin

# 日志配置
logging:
  file:
    path: /root/product/data/zeta-kotlin
  config: classpath:logback-spring.xml
